function トップページに移動(event){document.getElementById('ons-splitter-content1').load('top.html');document.getElementById('ons-splitter-side1').close()}
function 注文に移動(event){document.getElementById('ons-splitter-content1').load('order.html');document.getElementById('ons-splitter-side1').close()}
function 写真に移動(event){document.getElementById('ons-splitter-content1').load('picture.html');document.getElementById('ons-splitter-side1').close()}
function 注文リストクリック(event){const checkbox=event.target.closest('ons-list-item').querySelector('ons-checkbox');checkbox.checked=!checkbox.checked;let total=0;const listItems=event.target.closest('ons-list').querySelectorAll('ons-list-item');listItems.forEach(item=>{if(item.querySelector('ons-checkbox').checked){const priceElement=item.closest('ons-list-item').querySelector('.right:last-child');const price=parseInt(priceElement.textContent.replace('¥',''));total+=price}});document.getElementById('div62').textContent=`合計： ${total} 円`}
function 確認ダイアログ表示(event){const onsDialog1=document.getElementById('ons-dialog1');onsDialog1.show()}
function 確認キャンセル(event){const onsDialog1=document.getElementById('ons-dialog1');onsDialog1.hide()}
document.addEventListener('init',(event)=>{let page=event.target;if(page.id==='ons-page3'){let onsbutton1_element=document.querySelector('#ons-button1');if(onsbutton1_element){onsbutton1_element.addEventListener('click',確認ダイアログ表示);page.addEventListener('destroy',function(event){onsbutton1_element.removeEventListener('click',確認ダイアログ表示)},{'once':!0})}
let onsbutton3_element=document.querySelector('#ons-button3');if(onsbutton3_element){onsbutton3_element.addEventListener('click',確認キャンセル);page.addEventListener('destroy',function(event){onsbutton3_element.removeEventListener('click',確認キャンセル)},{'once':!0})}
let onslistitem2_element=document.querySelector('#ons-list-item2');if(onslistitem2_element){onslistitem2_element.addEventListener('click',注文リストクリック);page.addEventListener('destroy',function(event){onslistitem2_element.removeEventListener('click',注文リストクリック)},{'once':!0})}
let onslistitem3_element=document.querySelector('#ons-list-item3');if(onslistitem3_element){onslistitem3_element.addEventListener('click',注文リストクリック);page.addEventListener('destroy',function(event){onslistitem3_element.removeEventListener('click',注文リストクリック)},{'once':!0})}
let onslistitem5_element=document.querySelector('#ons-list-item5');if(onslistitem5_element){onslistitem5_element.addEventListener('click',注文リストクリック);page.addEventListener('destroy',function(event){onslistitem5_element.removeEventListener('click',注文リストクリック)},{'once':!0})}
let onslistitem4_element=document.querySelector('#ons-list-item4');if(onslistitem4_element){onslistitem4_element.addEventListener('click',注文リストクリック);page.addEventListener('destroy',function(event){onslistitem4_element.removeEventListener('click',注文リストクリック)},{'once':!0})}}});document.addEventListener('init',(event)=>{let page=event.target;if(page.id==='ons-page2'){let onslistitem1_element=document.querySelector('#ons-list-item1');if(onslistitem1_element){onslistitem1_element.addEventListener('click',トップページに移動);page.addEventListener('destroy',function(event){onslistitem1_element.removeEventListener('click',トップページに移動)},{'once':!0})}
let onslistitem6_element=document.querySelector('#ons-list-item6');if(onslistitem6_element){onslistitem6_element.addEventListener('click',注文に移動);page.addEventListener('destroy',function(event){onslistitem6_element.removeEventListener('click',注文に移動)},{'once':!0})}
let onslistitem7_element=document.querySelector('#ons-list-item7');if(onslistitem7_element){onslistitem7_element.addEventListener('click',写真に移動);page.addEventListener('destroy',function(event){onslistitem7_element.removeEventListener('click',写真に移動)},{'once':!0})}}})