name: Create PMTiles

on:
  workflow_dispatch:

jobs:
  create-pmtiles:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            osmconvert \
            tippecanoe \
            wget \
            curl \
            build-essential \
            cmake \
            git \
            golang  # pmtilesはgoで書かれているため、golangが必要


      - name: Build tippecanoe
        run: |
            git clone --depth 1 https://github.com/mapbox/tippecanoe.git
            cd tippecanoe
            ./autogen.sh
            ./configure
            make
            sudo make install
            cd ..
            rm -rf tippecanoe

      - name: Build pmtiles
        run: |
            git clone --depth 1 https://github.com/maptiler/pmtiles.git
            cd pmtiles
            go build
            sudo mv pmtiles /usr/local/bin/
            cd ..
            rm -rf pmtiles

      - name: Build osmconvert
        run: |
            git clone --depth 1 https://github.com/osmcode/osmconvert.git
            cd osmconvert
            mkdir build
            cd build
            cmake ..
            make
            sudo make install
            cd ../..
            rm -rf osmconvert

      - name: Download OpenStreetMap data
        run: |
          wget -O tohoku-latest.osm.pbf $(curl -s https://download.geofabrik.de/asia/japan/tohoku.html | grep -oP 'href="\Kasia/japan/tohoku-latest\.osm\.pbf(?=")')

      - name: Create MBTiles
        run: |
          tippecanoe -f -o=tohoku.mbtiles -z14 -l osm tohoku-latest.osm.pbf

      - name: Convert to PMTiles
        run: |
          pmtiles convert tohoku.mbtiles tohoku.pmtiles

      - name: Upload PMTiles artifact
        uses: actions/upload-artifact@v3
        with:
          name: tohoku-pmtiles
          path: tohoku.pmtiles
