name: Create PMTiles

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: actions/docker@v3
        with:
          build-context: .
          dockerfile-path: Dockerfile
          push: true
          tags: ${{ github.repository }}-pmtiles-builder:${{ github.run_id }}

  create-pmtiles:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Download OpenStreetMap data
        run: |
          wget -O tohoku-latest.osm.pbf $(curl -s https://download.geofabrik.de/asia/japan/tohoku.html | grep -oP 'href="\Kasia/japan/tohoku-latest\.osm\.pbf(?=")')

      - name: Run Docker container
        uses: actions/docker@v3
        with:
          image: ${{ needs.build-image.outputs.image-tag }}
          entrypoint: |
            wget -O tohoku-latest.osm.pbf $(curl -s https://download.geofabrik.de/asia/japan/tohoku.html | grep -oP 'href="\Kasia/japan/tohoku-latest\.osm\.pbf(?=")')
            tippecanoe -f -o=tohoku.mbtiles -z14 -l osm tohoku-latest.osm.pbf
            pmtiles convert tohoku.mbtiles tohoku.pmtiles
          
      - name: Upload PMTiles artifact
        uses: actions/upload-artifact@v3
        with:
          name: tohoku-pmtiles
          path: tohoku.pmtiles
