name: Create PMTiles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: osrm/osrm-backend
    steps:
      - name: Download OpenStreetMap data
        run: |
          wget -O tohoku-latest.osm.pbf $(curl -s https://download.geofabrik.de/asia/japan/tohoku.html | grep -oP 'href="\Kasia/japan/tohoku-latest\.osm\.pbf(?=")')
          
      - name: Create MBTiles
        run: |
          tippecanoe -f -o=tohoku.mbtiles -z14 -l osm tohoku-latest.osm.pbf

      - name: Convert to PMTiles
        run: |
          pmtiles convert tohoku.mbtiles tohoku.pmtiles

      - name: Upload PMTiles artifact
        uses: actions/upload-artifact@v3
        with:
          name: tohoku-pmtiles
          path: tohoku.pmtiles
